# ============================================================
# application.properties - ms-productos360
# Microservicio de Productos - Pedidos360
# Puerto: 8081 (distinto al BFF que usa 8080)
# ============================================================
spring.application.name=ms-productos360
server.port=8081

# ============================================================
# BASE DE DATOS ORACLE AUTONOMOUS (OCI) - TNS Wallet
# Mismo Oracle que el BFF, distinto esquema/tabla (PRODUCTS)
# ============================================================
spring.datasource.url=jdbc:oracle:thin:@pedidos360_high?TNS_ADMIN=src/main/resources/wallet
spring.datasource.username=admin
spring.datasource.password=Va20918025-1
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.oracle.wallet.password=Va20918025-1

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=300000

# --- Hibernate / JPA ---
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# ============================================================
# AZURE ENTRA ID - VALIDACION JWT
# Mismo tenant/client que el BFF
# ============================================================
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/0b35a36d-71da-40b9-bf0e-6f6de270b817/v2.0

spring.cloud.azure.active-directory.enabled=true
spring.cloud.azure.active-directory.app-id-uri=api://a3557daf-0f04-458e-ba1e-79b5200583ef
spring.cloud.azure.active-directory.credential.client-id=a3557daf-0f04-458e-ba1e-79b5200583ef
spring.cloud.azure.active-directory.profile.tenant-id=0b35a36d-71da-40b9-bf0e-6f6de270b817

# ============================================================
# ACTUATOR
# ============================================================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when-authorized

# ============================================================
# LOGGING
# ============================================================
logging.level.org.springframework.security=DEBUG
logging.level.cl.duoc.pedidos360=DEBUG
logging.level.org.hibernate.SQL=DEBUG
